var  a = 1;
console.log("hello world");
var b = 2;
console.log("hello world2");
var c = 3;
console.log("hello world3");
var c = 4;
console.log("hello world4");
var c = 5;
console.log("hello world5");
var c = 7;
console.log("hello world7");
var c = 8;
console.log("add hello world8");
var c = 10;
console.log("add hello world10");
var c = 11;
console.log("add hello world11");
var c = 9;
console.log("add hello world9");
var c = 6;
console.log("hello world6");